spring.application.name=semana16-backend
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/semana16}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:semana16}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:semana16}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
